services:
  teamundspielerdb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=teamundspieler
      - POSTGRES_DB=teamUndSpielerdb
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 7070:8080
